name = "mou-endpoint"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2023-12-01"

rules = [{ type = "ESModule", globs = ["**/*.js", "**/*.mjs"] }]

[site]
bucket = ".output/public"


[[kv_namespaces]]
binding = "KV_STORAGE"
id = "17b42a11c12748629254b70cc46ba084"

[[d1_databases]]
binding = "DB"
database_name = "api-database"
database_id = "138ef67c-8cd5-4b40-9dc1-1503b62c1175"

[[r2_buckets]]
binding = "FILE_BLOB"
bucket_name = "file-blob"
